//let b = 3;

try {
    let a = 2 + b;
} catch(erro){
    console.log(erro);
} finally {
    console.log("Executou")
}